const filmResponse = {
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/stKGOm8UyhuLPR9sZLjs5AkmncA.jpg",
      "genre_ids": [16, 10751, 12, 35, 18],
      "id": 1022789,
      "original_language": "en",
      "original_title": "Inside Out 2",
      "overview":
          "Il film torna nella mente dell'adolescente Riley proprio quando il quartier generale viene improvvisamente demolito per far posto a qualcosa di completamente inaspettato: nuove Emozioni! Gioia, Tristezza, Rabbia, Paura e Disgusto, che a detta di tutti gestiscono da tempo un'attività di successo, non sanno come comportarsi quando arriva Ansia. E sembra che non sia sola.",
      "popularity": 7738.12,
      "poster_path": "/hsyNR14TSGklwoHFjPZnPiu6UlV.jpg",
      "release_date": "2024-06-11",
      "title": "Inside Out 2",
      "video": false,
      "vote_average": 7.716,
      "vote_count": 1610
    },
    {
      "adult": false,
      "backdrop_path": "/zYdVEWpZyG1S1BtMEdOl2W36I7A.jpg",
      "genre_ids": [16, 10751, 35, 28],
      "id": 519182,
      "original_language": "en",
      "original_title": "Despicable Me 4",
      "overview":
          "Gru e Lucy e le loro figlie - Margo, Edith e Agnes - accolgono un nuovo membro nella famiglia, Gru Jr., deciso a far disperare suo padre. Gru affronta un nuovo nemico, Maxime Le Mal e la fidanzata, la femme fatale Valentina, per cui la famiglia sarà costretta alla fuga.",
      "popularity": 6006.489,
      "poster_path": "/898BC1HabQvEphWLhuhXY6ui5SG.jpg",
      "release_date": "2024-06-20",
      "title": "Cattivissimo me 4",
      "video": false,
      "vote_average": 7.591,
      "vote_count": 182
    },
    {
      "adult": false,
      "backdrop_path": "/fqv8v6AycXKsivp1T5yKtLbGXce.jpg",
      "genre_ids": [878, 12, 28],
      "id": 653346,
      "original_language": "en",
      "original_title": "Kingdom of the Planet of the Apes",
      "overview":
          "Diverse generazioni nel futuro dopo il regno di Cesare, le scimmie sono ora la specie dominante che vive armoniosamente e gli umani sono stati ridotti a vivere nell'ombra. Mentre un nuovo tirannico capo scimmia costruisce il suo impero, una giovane scimmia intraprende un viaggio straziante che la porterà a mettere in discussione tutto ciò che ha conosciuto del passato e a fare delle scelte che definiranno un futuro sia per le scimmie che per gli umani.",
      "popularity": 2365.896,
      "poster_path": "/nHAmd6yp025PqjHGD3VzfBssxFp.jpg",
      "release_date": "2024-05-08",
      "title": "Il regno del pianeta delle scimmie",
      "video": false,
      "vote_average": 7,
      "vote_count": 1594
    },
    {
      "adult": false,
      "backdrop_path": "/wNAhuOZ3Zf84jCIlrcI6JhgmY5q.jpg",
      "genre_ids": [28, 12, 878],
      "id": 786892,
      "original_language": "en",
      "original_title": "Furiosa: A Mad Max Saga",
      "overview":
          "Mentre il mondo va in rovina, la giovane Furiosa viene strappata dal Luogo Verde delle Molte Madri, e cade nelle mani di una grande Orda di Motociclisti guidata dal Signore della Guerra Dementus. Attraversando le Terre Desolate, si imbattono nella Cittadella presieduta da Immortan Joe. Mentre i due tiranni si battono per il predominio, Furiosa deve sopravvivere a molte prove e mettere insieme i mezzi per trovare la strada di casa.",
      "popularity": 2397.135,
      "poster_path": "/uYfY4dpVCdsuWd6v4cR7W1RBTDS.jpg",
      "release_date": "2024-05-22",
      "title": "Furiosa - A Mad Max Saga",
      "video": false,
      "vote_average": 7.669,
      "vote_count": 2016
    },
    {
      "adult": false,
      "backdrop_path": "/buawWBeKYjYfeiPoS2jIcjOrghZ.jpg",
      "genre_ids": [27, 53],
      "id": 1214509,
      "original_language": "en",
      "original_title": "In a Violent Nature",
      "overview": "",
      "popularity": 1347.111,
      "poster_path": "/hPfWHgq07nXbeldwEGxWB4JqwtE.jpg",
      "release_date": "2024-05-31",
      "title": "In a Violent Nature",
      "video": false,
      "vote_average": 5.691,
      "vote_count": 81
    },
    {
      "adult": false,
      "backdrop_path": "/rrwt0u1rW685u9bJ9ougg5HJEHC.jpg",
      "genre_ids": [28, 35, 80],
      "id": 280180,
      "original_language": "en",
      "original_title": "Beverly Hills Cop: Axel F",
      "overview":
          "Quarant'anni dopo il suo indimenticabile primo caso a Beverly Hills, il poliziotto di Detroit Axel Foley torna a fare ciò in cui eccelle: risolvere crimini e seminare il caos.",
      "popularity": 1800.959,
      "poster_path": "/rUCcqsvEJsCX0IgucHKBAlmgHgu.jpg",
      "release_date": "2024-06-20",
      "title": "Un piedipiatti a Beverly Hills: Axel F",
      "video": false,
      "vote_average": 6.944,
      "vote_count": 440
    },
    {
      "adult": false,
      "backdrop_path": "/P82NAcEsLIYgQtrtn36tYsj41m.jpg",
      "genre_ids": [16, 35, 10751, 12],
      "id": 748783,
      "original_language": "en",
      "original_title": "The Garfield Movie",
      "overview":
          "Garfield, il famoso gatto di casa che odia il lunedì e ama le lasagne, sta per vivere un’avventura selvaggia all’aria aperta! Dopo un inaspettato ricongiungimento con il padre scomparso da tempo, il trasandato gatto di strada Vic, Garfield e il suo amico canino Odie sono costretti ad abbandonare la loro vita domestica per unirsi a Vic in una esilarante rapina ad alto rischio.",
      "popularity": 1553.504,
      "poster_path": "/4EK8RVhSx3G0aNrkmOTvuchGVHs.jpg",
      "release_date": "2024-04-30",
      "title": "Garfield - Una missione gustosa",
      "video": false,
      "vote_average": 7.135,
      "vote_count": 303
    },
    {
      "adult": false,
      "backdrop_path": "/gRApXuxWmO2forYTuTmcz5RaNUV.jpg",
      "genre_ids": [28, 80, 53, 35],
      "id": 573435,
      "original_language": "en",
      "original_title": "Bad Boys: Ride or Die",
      "overview":
          "Quest'estate, i “Bad Boys” più amati del mondo tornano con il loro iconico mix di azione e ironia sfrenata, ma questa volta con un colpo di scena: i due fuoriclasse di Miami sono ora i ricercati.",
      "popularity": 1310.469,
      "poster_path": "/9VRDZbTg9eAfY7ZqMyU1fbq897W.jpg",
      "release_date": "2024-06-05",
      "title": "Bad Boys: Ride or Die",
      "video": false,
      "vote_average": 7.018,
      "vote_count": 533
    },
    {
      "adult": false,
      "backdrop_path": "/jvPMJ2zM92jfXxVEFsqP1MMrLaO.jpg",
      "genre_ids": [878, 28, 12],
      "id": 823464,
      "original_language": "en",
      "original_title": "Godzilla x Kong: The New Empire",
      "overview":
          "L'epica battaglia continua! Una nuovissima avventura che vedrà l'onnipotente Kong e il temibile Godzilla combattere fianco a fianco contro una colossale minaccia sconosciuta che si cela nel nostro mondo, mettendo a dura prova la loro stessa esistenza... e la nostra. \"Godzilla e Kong - Il nuovo Impero\" approfondisce ulteriormente le storie e le origini di questi due Titani, nonché i misteri di Skull Island, tra gli altri, svelando la mitica battaglia che ha contribuito a forgiare questi esseri straordinari e li ha legati per sempre all'umanità.",
      "popularity": 941.534,
      "poster_path": "/2iezS60gl7L1jauBSTSy9davvlK.jpg",
      "release_date": "2024-03-27",
      "title": "Godzilla e Kong - Il nuovo impero",
      "video": false,
      "vote_average": 7.206,
      "vote_count": 3128
    },
    {
      "adult": false,
      "backdrop_path": "/iTWrsOVsUqcwYSxrpINNs3hG2nC.jpg",
      "genre_ids": [53, 27, 28, 9648],
      "id": 1001311,
      "original_language": "fr",
      "original_title": "Sous la Seine",
      "overview":
          "Per salvare Parigi da un bagno di sangue internazionale, una scienziata in lutto deve affrontare il suo passato quando uno squalo gigante compare nella Senna.",
      "popularity": 882.039,
      "poster_path": "/ty7tl4h34bfqqa2g09SaObFhFW7.jpg",
      "release_date": "2024-06-04",
      "title": "Under Paris",
      "video": false,
      "vote_average": 6.089,
      "vote_count": 872
    },
    {
      "adult": false,
      "backdrop_path": "/upk042Tms2EBfIzJf13OtOej0sd.jpg",
      "genre_ids": [10752, 28, 18],
      "id": 929590,
      "original_language": "en",
      "original_title": "Civil War",
      "overview":
          "In un'America sull'orlo del collasso, attraverso terre desolate e città distrutte dall’esplosione di una guerra civile, un gruppo di reporter intraprende un viaggio in condizioni estreme, mettendo a rischio le proprie vite per raccontare la verità.",
      "popularity": 716.15,
      "poster_path": "/vST6kIlOO2fJLtkonUErSpU83pk.jpg",
      "release_date": "2024-04-10",
      "title": "Civil War",
      "video": false,
      "vote_average": 6.999,
      "vote_count": 1852
    },
    {
      "adult": false,
      "backdrop_path": "/6XjMwQTvnICBz6TguiDKkDVHvgS.jpg",
      "genre_ids": [27, 878, 53],
      "id": 762441,
      "original_language": "en",
      "original_title": "A Quiet Place: Day One",
      "overview":
          "Mentre New York City è invasa da creature aliene che cacciano attraverso il suono, una donna di nome Sammy lotta per sopravvivere.",
      "popularity": 738.012,
      "poster_path": "/yg6wUGOiDhc2MFUrFeMNDHLJl6p.jpg",
      "release_date": "2024-06-26",
      "title": "A Quiet Place - Giorno 1",
      "video": false,
      "vote_average": 6.898,
      "vote_count": 373
    },
    {
      "adult": false,
      "backdrop_path": "/lA6KdSkCTxwzvqzPqxch997RabQ.jpg",
      "genre_ids": [28, 53],
      "id": 560016,
      "original_language": "en",
      "original_title": "Monkey Man",
      "overview":
          "Ispirato alla leggenda di Hanuman, simbolo di forza e coraggio. Kid è un giovane anonimo che si guadagna da vivere in un fight club clandestino dove, notte dopo notte, indossando una maschera da gorilla, viene picchiato a sangue da lottatori più famosi in cambio di denaro. Dopo anni di rabbia repressa, Kid scopre un modo per infiltrarsi nell'enclave della sinistra élite della città. Mentre il suo trauma infantile ribolle, le sue mani misteriosamente sfregiate scatenano una esplosiva ondata di vendetta per regolare i conti con gli uomini che gli hanno tolto tutto.",
      "popularity": 994.728,
      "poster_path": "/k4LPOpZN2BSHYFbbm58cbNFPAdI.jpg",
      "release_date": "2024-04-03",
      "title": "Monkey Man",
      "video": false,
      "vote_average": 7.083,
      "vote_count": 570
    },
    {
      "adult": false,
      "backdrop_path": "/aATi2PtaOQCVAquCym6OU0Z4FjY.jpg",
      "genre_ids": [28, 80, 53],
      "id": 704673,
      "original_language": "en",
      "original_title": "Trigger Warning",
      "overview":
          "Un'agente delle forze speciali svela un pericoloso complotto dopo essere tornata nella città natale in cerca di risposte sulla morte dell'amato padre.",
      "popularity": 689.064,
      "poster_path": "/bDvrCDJpBFF8NZstK9jsRSkSwnc.jpg",
      "release_date": "2024-06-20",
      "title": "Trigger Warning",
      "video": false,
      "vote_average": 5.878,
      "vote_count": 300
    },
    {
      "adult": false,
      "backdrop_path": "/j29ekbcLpBvxnGk6LjdTc2EI5SA.jpg",
      "genre_ids": [16, 10751, 12, 18, 35],
      "id": 150540,
      "original_language": "en",
      "original_title": "Inside Out",
      "overview":
          "Riley ha undici anni e una vita felice. Divisa tra l'amica e due genitori adorabili cresce assieme alle sue emozioni che la consigliano, la incoraggiano, la contengono, la spazientiscono, la intristiscono, la infastidiscono. Dentro la sua testa e dietro ai pulsanti della console emozionale governa Joy, sempre positiva e intraprendente, si spazientisce Anger, sempre pronto alla rissa, si turba Fear, sempre impaurito e impedito, si immalinconisce Sadness, sempre triste e sfiduciata, arriccia il naso Disgust, sempre disgustata e svogliata. Trasferiti dal Minnesota a San Francisco, Riley e genitori provano ad adattarsi alla nuova vita. Il debutto a scuola e il camion del trasloco perduto nel Texas, mettono però a dura prova le loro emozioni. A peggiorare le cose ci pensano Sadness e Joy, la prima ostinata a partecipare ai cambiamenti emotivi di Riley, la seconda risoluta a garantirle un'imperturbabile felicità. Ma la vita non è mai così semplice.",
      "popularity": 645.446,
      "poster_path": "/1LZMmVOVsP9SWJDhEZiY9cCMNyp.jpg",
      "release_date": "2015-06-17",
      "title": "Inside Out",
      "video": false,
      "vote_average": 7.916,
      "vote_count": 21152
    },
    {
      "adult": false,
      "backdrop_path": "/yHEFwHkU2NqRxBrAoGBfuhuqIL1.jpg",
      "genre_ids": [35, 28],
      "id": 1143019,
      "original_language": "fr",
      "original_title": "Les Infaillibles",
      "overview":
          "Quando una banda di rapinatori scatena il caos a Parigi e umilia la polizia, il ministro vuole nuovi uomini al comando delle indagini: Alia è di Marsiglia, ha un carattere impetuoso ed è ingestibile, Hugo è parigino, laureato e meticoloso. In breve, hanno tutti i motivi per odiarsi a vicenda. Un'alleanza forzata, nel bene e nel male, o forse sboccerà diventando qualcos'altro?",
      "popularity": 632.945,
      "poster_path": "/wFDHp6kyZ1xZu7D2HL1NRF80V8p.jpg",
      "release_date": "2024-06-20",
      "title": "Gli Infallibili",
      "video": false,
      "vote_average": 5.848,
      "vote_count": 46
    },
    {
      "adult": false,
      "backdrop_path": "/fZv4EldEPurSz0d2uVIoL4Sng8x.jpg",
      "genre_ids": [28, 18, 53],
      "id": 1016346,
      "original_language": "bn",
      "original_title": "MR-9: Do or Die",
      "overview":
          "Una spia d'élite del Bangladesh si unisce a un agente della CIA per abbattere un'organizzazione criminale internazionale guidata da uno spietato uomo d'affari.",
      "popularity": 636.073,
      "poster_path": "/yF2g3MDacpZTMywh97qghW6Y0H4.jpg",
      "release_date": "2023-08-25",
      "title": "MR-9: Do or Die",
      "video": false,
      "vote_average": 6.528,
      "vote_count": 107
    },
    {
      "adult": false,
      "backdrop_path": "/3ffPx9jqg0yj9y1KWeagT7D20CB.jpg",
      "genre_ids": [16, 28, 10751, 35, 14],
      "id": 1011985,
      "original_language": "en",
      "original_title": "Kung Fu Panda 4",
      "overview":
          "Po è destinato a diventare il nuovo leader spirituale della Valle della Pace, ma prima di poterlo fare, deve trovare un successore per diventare il nuovo Guerriero Drago. Sembra trovarne uno in Zhen, una volpe con molte abilità promettenti ma a cui non piace l'idea che Po lo alleni.",
      "popularity": 652.863,
      "poster_path": "/hXx9YEJzRhronB6jtfpzVh19WhY.jpg",
      "release_date": "2024-03-02",
      "title": "Kung Fu Panda 4",
      "video": false,
      "vote_average": 7.132,
      "vote_count": 2253
    },
    {
      "adult": false,
      "backdrop_path": "/5Aks5cCqHG8xFLoUSLsfGdVfIC.jpg",
      "genre_ids": [14, 9648, 53, 27],
      "id": 1086747,
      "original_language": "en",
      "original_title": "The Watchers",
      "overview":
          "Il film segue le vicende di Mina, artista di 28 anni, che si ritrova bloccata e isolata in una vasta e incontaminata foresta nell’Irlanda occidentale. Quando Mina trova un riparo, rimane inconsapevolmente intrappolata assieme a tre sconosciuti che ogni notte sono spiati e perseguitati da misteriose creature.",
      "popularity": 541.929,
      "poster_path": "/6nNAAlWwHJHSISfiMD19jFDUwOg.jpg",
      "release_date": "2024-06-06",
      "title": "The Watchers - Loro ti guardano",
      "video": false,
      "vote_average": 6.6,
      "vote_count": 446
    },
    {
      "adult": false,
      "backdrop_path": "/vblTCXOWUQGSc837vgbhDRi4HSc.jpg",
      "genre_ids": [28, 80, 35, 53],
      "id": 955555,
      "original_language": "ko",
      "original_title": "범죄도시 3",
      "overview":
          "Il detective Ma Seok-do si unisce alla Cyber Investigation Team per arrestare Baek Chang-ki, ex mercenario e capo di un'organizzazione di gioco d'azzardo online.",
      "popularity": 543.051,
      "poster_path": "/kPtNokhBtgwSp3MHaR3X4O0SPbF.jpg",
      "release_date": "2023-05-31",
      "title": "범죄도시 3",
      "video": false,
      "vote_average": 7.3,
      "vote_count": 358
    }
  ],
  "total_pages": 45059,
  "total_results": 901172
};
