name: flutter_architecture
description: "Flutter Architecture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.7.0
  go_router: ^14.2.3
  view:
    path: ./view
  view_model:
    path: ./view_model
  model:
    path: ./model

dev_dependencies:
  flutter_lints: ^4.0.0
  go_router_builder: ^2.7.1
  build_runner: ^2.4.12

flutter:
  uses-material-design: true