name: flutter_architecture
description: "Flutter Architecture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.5.0+1
  get_it: ^7.7.0
  go_router: ^14.2.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  go_router_builder: ^2.7.1
  build_runner: ^2.4.12

flutter_gen:
  output: lib/generated/

flutter:
  uses-material-design: true
  generate: true