const relatedFilmResponse = {
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/aXPCXYFzFzdveVVk1HjVf9fHUcn.jpg",
      "genre_ids": [878, 28],
      "id": 1103,
      "original_language": "en",
      "original_title": "Escape from New York",
      "overview":
          "In a world ravaged by crime, the entire island of Manhattan has been converted into a walled prison where brutal prisoners roam. After the US president crash-lands inside, war hero Snake Plissken has 24 hours to bring him back.",
      "popularity": 66.568,
      "poster_path": "/yreqWiQ7IOkXWVB2Tz4LJIs7xqA.jpg",
      "release_date": "1981-05-23",
      "title": "Escape from New York",
      "video": false,
      "vote_average": 7.072,
      "vote_count": 3022
    },
    {
      "adult": false,
      "backdrop_path": "/yOGELMEm6DPkdrBoJ7JbsyByCbn.jpg",
      "genre_ids": [16, 35, 10751],
      "id": 1267,
      "original_language": "en",
      "original_title": "Meet the Robinsons",
      "overview":
          "Lewis, a brilliant young inventor, is keen on creating a time machine to find his mother, who abandoned him in an orphanage. Things take a turn when he meets Wilbur Robinson and his family.",
      "popularity": 61.59,
      "poster_path": "/naya0zF4kT401Sx15AtwB9vpcJr.jpg",
      "release_date": "2007-03-23",
      "title": "Meet the Robinsons",
      "video": false,
      "vote_average": 6.9,
      "vote_count": 2765
    },
    {
      "adult": false,
      "backdrop_path": "/92mpNNg6v2PN2HN2C2Z4g0v3Tya.jpg",
      "genre_ids": [12, 16, 35, 10751],
      "id": 1273,
      "original_language": "en",
      "original_title": "TMNT",
      "overview":
          "After the defeat of their old arch nemesis, The Shredder, the Turtles have grown apart as a family. Struggling to keep them together, their rat sensei, Splinter, becomes worried when strange things begin to brew in New York City.",
      "popularity": 46.418,
      "poster_path": "/6ZCWn7BGpDLBDigtdiuGyBdEqab.jpg",
      "release_date": "2007-03-23",
      "title": "TMNT",
      "video": false,
      "vote_average": 6.142,
      "vote_count": 1063
    },
    {
      "adult": false,
      "backdrop_path": "/xh820ngf1lauGQuFiTvzYuCe6vj.jpg",
      "genre_ids": [28, 12, 53, 10752],
      "id": 1369,
      "original_language": "en",
      "original_title": "Rambo: First Blood Part II",
      "overview":
          "John Rambo is released from prison by the government for a top-secret covert mission to the last place on Earth he'd want to return - the jungles of Vietnam.",
      "popularity": 81.477,
      "poster_path": "/pzPdwOitmTleVE3YPMfIQgLh84p.jpg",
      "release_date": "1985-05-21",
      "title": "Rambo: First Blood Part II",
      "video": false,
      "vote_average": 6.638,
      "vote_count": 3771
    },
    {
      "adult": false,
      "backdrop_path": "/ncEsesgOJDNrTUED89hYbA117wo.jpg",
      "genre_ids": [28, 878],
      "id": 603,
      "original_language": "en",
      "original_title": "The Matrix",
      "overview":
          "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
      "popularity": 90.586,
      "poster_path": "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
      "release_date": "1999-03-31",
      "title": "The Matrix",
      "video": false,
      "vote_average": 8.216,
      "vote_count": 25137
    },
    {
      "adult": false,
      "backdrop_path": "/pxK1iK6anS6erGg4QePmMKbB1E7.jpg",
      "genre_ids": [12, 28, 53, 878],
      "id": 604,
      "original_language": "en",
      "original_title": "The Matrix Reloaded",
      "overview":
          "Six months after the events depicted in The Matrix, Neo has proved to be a good omen for the free humans, as more and more humans are being freed from the matrix and brought to Zion, the one and only stronghold of the Resistance.  Neo himself has discovered his superpowers including super speed, ability to see the codes of the things inside the matrix and a certain degree of pre-cognition. But a nasty piece of news hits the human resistance: 250,000 machine sentinels are digging to Zion and would reach them in 72 hours. As Zion prepares for the ultimate war, Neo, Morpheus and Trinity are advised by the Oracle to find the Keymaker who would help them reach the Source.  Meanwhile Neo's recurrent dreams depicting Trinity's death have got him worried and as if it was not enough, Agent Smith has somehow escaped deletion, has become more powerful than before and has fixed Neo as his next target.",
      "popularity": 52.482,
      "poster_path": "/9TGHDvWrqKBzwDxDodHYXEmOE6J.jpg",
      "release_date": "2003-05-15",
      "title": "The Matrix Reloaded",
      "video": false,
      "vote_average": 7.052,
      "vote_count": 10697
    },
    {
      "adult": false,
      "backdrop_path": "/533xAMhhVyjTy8hwMUFEt5TuDfR.jpg",
      "genre_ids": [12, 28, 53, 878],
      "id": 605,
      "original_language": "en",
      "original_title": "The Matrix Revolutions",
      "overview":
          "The human city of Zion defends itself against the massive invasion of the machines as Neo fights to end the war at another front while also opposing the rogue Agent Smith.",
      "popularity": 43.318,
      "poster_path": "/t1wm4PgOQ8e4z1C6tk1yDNrps4T.jpg",
      "release_date": "2003-11-05",
      "title": "The Matrix Revolutions",
      "video": false,
      "vote_average": 6.726,
      "vote_count": 9644
    },
    {
      "adult": false,
      "backdrop_path": "/6cwkM6dkWU4F9YM0JCIqLDK2Aue.jpg",
      "genre_ids": [27, 18, 14],
      "id": 628,
      "original_language": "en",
      "original_title": "Interview with the Vampire",
      "overview":
          "A vampire relates his epic life story of love, betrayal, loneliness, and dark hunger to an over-curious reporter.",
      "popularity": 69.758,
      "poster_path": "/2162lAT2MP36MyJd2sttmj5du5T.jpg",
      "release_date": "1994-11-11",
      "title": "Interview with the Vampire",
      "video": false,
      "vote_average": 7.4,
      "vote_count": 5666
    },
    {
      "adult": false,
      "backdrop_path": "/nRsr98MFztBGm532hCVMGXV6qOp.jpg",
      "genre_ids": [12, 14, 10751],
      "id": 630,
      "original_language": "en",
      "original_title": "The Wizard of Oz",
      "overview":
          "Young Dorothy finds herself in a magical world where she makes friends with a lion, a scarecrow and a tin man as they make their way along the yellow brick road to talk with the Wizard and ask for the things they miss most in their lives. The Wicked Witch of the West is the only thing that could stop them.",
      "popularity": 58.151,
      "poster_path": "/pfAZFD7I2hxW9HCChTuAzsdE6UX.jpg",
      "release_date": "1939-08-15",
      "title": "The Wizard of Oz",
      "video": false,
      "vote_average": 7.587,
      "vote_count": 5392
    },
    {
      "adult": false,
      "backdrop_path": "/akXPz7zK6NZ8YxGqjcHunGK9bXL.jpg",
      "genre_ids": [28, 80, 53],
      "id": 393,
      "original_language": "en",
      "original_title": "Kill Bill: Vol. 2",
      "overview":
          "The Bride unwaveringly continues on her roaring rampage of revenge against the band of assassins who had tried to kill her and her unborn child. She visits each of her former associates one-by-one, checking off the victims on her Death List Five until there's nothing left to do … but kill Bill.",
      "popularity": 61.064,
      "poster_path": "/2yhg0mZQMhDyvUQ4rG1IZ4oIA8L.jpg",
      "release_date": "2004-04-16",
      "title": "Kill Bill: Vol. 2",
      "video": false,
      "vote_average": 7.879,
      "vote_count": 13547
    },
    {
      "adult": false,
      "backdrop_path": "/94G3s3tvLkYcDgEdfJFQwOwOPHt.jpg",
      "genre_ids": [80, 28],
      "id": 222245,
      "original_language": "cn",
      "original_title": "硬漢",
      "overview":
          "An eastern by Joseph Velasco. Two undercover agents must smash a smuggling racket that is terrorizing a small port town. One of the agents, Chin Chang, has an evil grip that can crush a skull in seconds. The thugs are killers but this agent is a killer in kung fu!",
      "popularity": 11.469,
      "poster_path": "/2L6Xj09E7Wp0itz3HmkHFni1dYz.jpg",
      "release_date": "1972-10-19",
      "title": "Revenge of the Dragon",
      "video": false,
      "vote_average": 6,
      "vote_count": 1
    },
    {
      "adult": false,
      "backdrop_path": "/uHTjgDGom9iOoUZke86gqMjBUgy.jpg",
      "genre_ids": [12, 16, 35, 14],
      "id": 223702,
      "original_language": "en",
      "original_title": "Sausage Party",
      "overview":
          "Hot dog Frank leads a group of supermarket products on a quest to discover the truth about their existence and what really happens when they become chosen to leave the grocery store.",
      "popularity": 69.341,
      "poster_path": "/vNgdPJQ5CI60oEiiHLKRNrsDhMy.jpg",
      "release_date": "2016-07-11",
      "title": "Sausage Party",
      "video": false,
      "vote_average": 5.7,
      "vote_count": 7079
    },
    {
      "adult": false,
      "backdrop_path": "/z8QUJqeZyfyAMBjb6zGtvtkuSpQ.jpg",
      "genre_ids": [28],
      "id": 223760,
      "original_language": "en",
      "original_title": "Fist of the Dragon",
      "overview":
          "Damon, an MMA fighter retires and goes to China to meet his new love, Meili. But things take an immediate turn when he inadvertently takes a package sought by an underground arms dealer. Now he must fight to save himself and his loved one.",
      "popularity": 4.75,
      "poster_path": "/g1JOwVfQPUwI2BVDPrEnpaKlX9t.jpg",
      "release_date": "2014-10-09",
      "title": "Fist of the Dragon",
      "video": false,
      "vote_average": 3.8,
      "vote_count": 2
    },
    {
      "adult": false,
      "backdrop_path": "/bJcD8d58JWUpHB2tZl7ykDohtJB.jpg",
      "genre_ids": [27, 35],
      "id": 695962,
      "original_language": "hi",
      "original_title": "भूल भुलैया 2",
      "overview":
          "When strangers Reet and Ruhan cross paths, their journey leads to an abandoned mansion and a dreaded spirit who has been trapped for 18 years.",
      "popularity": 27.196,
      "poster_path": "/fw0oMHiMt9qOuKEJEmzFiCNAnXc.jpg",
      "release_date": "2022-05-20",
      "title": "Bhool Bhulaiyaa 2",
      "video": false,
      "vote_average": 6.3,
      "vote_count": 64
    },
    {
      "adult": false,
      "backdrop_path": "/4AMAfqTnYsYESpZwJ3eXAOKg4al.jpg",
      "genre_ids": [35, 80],
      "id": 696047,
      "original_language": "ko",
      "original_title": "시민덕희",
      "overview":
          "After losing her laundry store to a fire incident, a single mom Duk-hee receives a call from a bank offering a generous upfront loan so she takes it right away. But soon after, she finds out that she has become a victim of a voice phishing scheme. Devastated, Duk-hee turns to the police for help, only to be more disappointed that there is no hope of retrieving her money. At the moment of despair, Jae-min, the phisher who tricked her, rings her phone once again to tip Duk-hee off about the criminal organization that locked him up and coerced him to make voice phishing calls from China. With that call, Duk-hee makes up her mind to investigate this case for herself and take a plane to China with her friends.",
      "popularity": 27.225,
      "poster_path": "/h9Kdc6o7v3d7tVXyT6QndVYlaeD.jpg",
      "release_date": "2024-01-24",
      "title": "Citizen of a Kind",
      "video": false,
      "vote_average": 7.25,
      "vote_count": 18
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [28],
      "id": 696192,
      "original_language": "cn",
      "original_title": "踢窦",
      "overview":
          "When a gang war breaks out over disputed territory, crime boss Wai blames his lieutenant, Ah Sing, for failing to wipe out the competition.",
      "popularity": 5.755,
      "poster_path": "/nw2TdWZ9fUbXhgB0oq6sRkuFdfa.jpg",
      "release_date": "1980-04-24",
      "title": "Duel of the Brave Ones",
      "video": false,
      "vote_average": 2,
      "vote_count": 1
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [28, 12],
      "id": 696196,
      "original_language": "zh",
      "original_title": "Guo guan zhan jiang",
      "overview":
          "Rebels try use the smuggling route to get the gold and map past the corrupt officials. Everybody was kung fu fighting.",
      "popularity": 10.773,
      "poster_path": "/w2AbwzWgHZG9No6wKHVVNlaYNUm.jpg",
      "release_date": "1973-07-19",
      "title": "Duel of the Dragons",
      "video": false,
      "vote_average": 0,
      "vote_count": 0
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [28],
      "id": 224274,
      "original_language": "en",
      "original_title": "Murder in the Orient",
      "overview":
          "American agent, with the help of a wise martial arts teacher, hunts down a pair of samurai swords that are worth millions of dollars.",
      "popularity": 4.064,
      "poster_path": "/hGh23MdmhxL6WZiRGDfimQ5l2so.jpg",
      "release_date": "1974-03-15",
      "title": "Murder in the Orient",
      "video": false,
      "vote_average": 5,
      "vote_count": 2
    },
    {
      "adult": false,
      "backdrop_path": "/nTdxvadei9THYNRgaCW9cbgd8XU.jpg",
      "genre_ids": [18, 35],
      "id": 1175852,
      "original_language": "en",
      "original_title": "Lovebugs",
      "overview":
          "“Would you like to hear a story?” From his cozy library inside the walls of a suburban home an intellectual snail tells of his life’s love, loss and change.",
      "popularity": 2.115,
      "poster_path": "/4UuyPbqxi5TJJF53wT2m0RCzbfR.jpg",
      "release_date": "2023-09-13",
      "title": "Lovebugs",
      "video": false,
      "vote_average": 0,
      "vote_count": 0
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [16, 10751, 80, 35],
      "id": 1175942,
      "original_language": "en",
      "original_title": "The Bad Guys 2",
      "overview":
          "The Bad Guys are struggling to find trust and acceptance in their newly minted lives as Good Guys, when they are pulled out of retirement and forced to do ‘one last job’ by an all-female squad of criminals.",
      "popularity": 15.278,
      "poster_path": "/5ezAFnjpRLoZMwmVdBFqLj9AJnk.jpg",
      "release_date": "2025-07-31",
      "title": "The Bad Guys 2",
      "video": false,
      "vote_average": 0,
      "vote_count": 0
    }
  ],
  "total_pages": 12291,
  "total_results": 245801
};
