name: view_model
description: "A new Flutter project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  model:
    path: ../model

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0