name: view
description: "A new Flutter project."
version: 0.0.1

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  intl: ^0.19.0
  view_model:
    path: ../view_model

dev_dependencies:
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/generated/
  assets:
    outputs:
      package_parameter_enabled: true

flutter:
  assets:
    - assets/
  generate: true
